### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by ha666** [casbin/casdoor#122] opened 2021-06-20 02:06 UTC
OS：windows 7
node.js：v13.14.0
npm：6.14.4

```shell
D:\proj\casdoor\web>npm install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will
 no longer receive updates.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 1
5x less dependencies.
npm WARN deprecated @types/testing-library__dom@7.5.0: This is a stub types definition. testing-libr
ary__dom provides its own type definitions, so you do not need this installed.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure
binaries. Upgrade to fsevents 2.
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer mai
ntained. Please use @rollup/plugin-babel.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported
or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or
 maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or
 maintained
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usa
ge due to the number of issues. Because of the V8 engine whims, feature detection in old core-js ver
sions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependen
cies to the actual version of core-js.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2021-06-20T02_01_53_661Z-debug.log
```

2021-06-20T02_01_53_661Z-debug.log
```log
35497 http fetch GET 200 https://cdn.npm.taobao.org/axe-core/-/axe-core-4.2.2.tgz 99525ms
35498 silly extract axe-core@^4.0.2 extracted to D:\proj\casdoor\web\node_modules\.staging\axe-core-17c23a5f (112012ms)
35499 silly extract core-js@^2.4.0 extracted to D:\proj\casdoor\web\node_modules\.staging\core-js-6a4d047d (125777ms)
35500 silly extract core-js-pure@^3.14.0 extracted to D:\proj\casdoor\web\node_modules\.staging\core-js-pure-bfb8da57 (137299ms)
35501 silly extract core-js@^3.6.5 extracted to D:\proj\casdoor\web\node_modules\.staging\core-js-305ffa3a (137036ms)
35502 silly extract @ant-design/icons-svg@^4.0.0 extracted to D:\proj\casdoor\web\node_modules\.staging\@ant-design\icons-svg-0cfbf6e2 (470850ms)
35503 silly extract @ant-design/icons@^4.6.2 extracted to D:\proj\casdoor\web\node_modules\.staging\@ant-design\icons-0de0d813 (302937ms)
35504 silly extract date-fns@^2.15.0 extracted to D:\proj\casdoor\web\node_modules\.staging\date-fns-51c0fbb4 (182906ms)
35505 timing npm Completed in 518709ms
35506 error cb() never called!
35507 error This is an error with npm itself. Please report this error at:
35508 error <https://npm.community>
```

**Comment by hsluoyz** [comment] 2021-06-20 02:32
@Kininaru @sh1luo

**Comment by sh1luo** [comment] 2021-06-20 02:55
hi @ha666, this may be caused by npm cache.
Try to do so in `web` directory:
```
rm -rf node_modules
sudo npm cache clean -f
npm install && npm run start
```

**Comment by hsluoyz** [comment] 2021-06-22 15:11
Closed as resolved.

**Closed by hsluoyz** 2021-06-22 15:11 UTC
Labels: question
